version: "3.9"

services:
  frontend:
    container_name: frontend
    build: ./docker/frontend
    volumes:
      - .:/app:cached
    ports:
      - "3003:3003"
    tty: true
    command: sh -c "npm install && npm run dev"
